name: 'PlatformIO Dependabot'
description: 'a Dependabot like script for PlatformIO'
inputs:
  github_token:
    description: 'Github Token'
    required: true
  assignee:
    description: 'Who to assign the pull request'
    required: false
  project_path:
    description: 'Path to PlatformIO Project. Default: current root dir'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.assignee }}
    - ${{ inputs.project_path }}
  entrypoint: "/app/entrypoint.sh"
